
Make = ['Jeep', 'GMC', 'Dodge', 'RAM', 'Nissan', 'Ford', 'Hyundai', 
        'Chevrolet', 'Volkswagen', 'Chrysler', 'Kia', 'Mazda', 'Acura',
        'Subaru', 'Audi', 'BMW', 'Toyota', 'Buick', 'Mercedes-Benz',
        'Honda', 'Lincoln', 'Cadillac', 'INFINITI', 'Lexus', 'Land Rover',
        'Volvo', 'Genesis', 'Jaguar']

Fuel = ['Gasoline', 'Diesel', 'Hybrid', 'Electric', 'E85 Flex Fuel',
        'PHEV Hybrid Fuel', 'Diesel (B20 capable)']

Transmission = ['8-Speed Automatic', 'Automatic', '6-Speed Automatic',
                'Automatic CVT', '10-Speed Automatic', 
                '8-Speed Automatic with Auto-Shift', '1-Speed Automatic',
               '7-Speed DSG Automatic with Tiptronic',
               '8-Speed Automatic with Tiptronic', '9-Speed Automatic',
               '8-speed automatic', 'CVT', '7-Speed Automatic S tronic',
               '7-Speed DSGA? Automatic w/ 4MO',
               '6-Speed Automatic Electronic with Overdrive',
               '9-Speed 948TE Automatic', '8-Speed A/T', 'Variable',
               '7-Speed Automatic with Auto-Shift', '9-Speed A/T',
               '9 Spd Automatic', 'Aisin 6-Speed Automatic',
               '6-Spd Aisin F21-250 PHEV Auto Trans', '62 kWh battery',
               '10-Speed Shiftable Automatic', '9-speed automatic',
               '6-SPEED AUTOMATIC', 'automatic w/paddle shifters', 'A/T',
               '8-Speed Shiftable Automatic', '6-Speed DCT Automatic',
               '1-Speed CVT with Overdrive', '6-Speed A/T', '(CVT) CONT VAR.',
               'CVT with Xtronic', '8 Speed Dual Clutch',
               '10-Speed Automatic with Overdrive', '8-Speed Automatic Sport']

Body = ['SUV', 'Pickup Truck', 'Sedan', 'Passenger Van', 'Cargo Van', 'Hatchback', 'Convertible', 'Minivan']

Drivetrain = ['Four-wheel Drive', 'All-wheel Drive', 'Rear-wheel Drive', 'Front-wheel Drive']

Model = ['Wagoneer', 'Grand Cherokee', 'Yukon XL', 'Durango', '3500',
        'Murano', 'F-350', 'Tucson Hybrid', 'Compass', 'Santa Cruz',
        'Blazer EV', 'Explorer', 'Taos', 'Jetta', 'Hornet', 'Tucson',
        'Terrain', 'Pacifica', '2500', 'Transit-250', 'Grand Cherokee 4xe',
           'EV6', 'Mustang Mach-E', 'Silverado 1500', 'Seltos', 'Blazer',
           'Wrangler', 'CX-90 PHEV', 'MDX', 'Outback', 'Atlas Cross Sport',
           'IONIQ 5', 'Q8 e-tron', 'Sonata Hybrid', 'EV9', 'Sportage Hybrid',
           'Expedition', 'Atlas', 'Grand Cherokee L', 'X7', 'Tundra Hybrid',
           'Kicks', 'Envista', 'Rogue', 'Wagoneer L', 'Sportage', 'EQE 350+',
           'Sonata', 'Ranger', 'SQ5', 'Q5 e', 'Charger', 'Sprinter 2500',
           'CR-V Hybrid', 'IONIQ 6', 'Transit-150', 'Santa Fe', 'Equinox',
           'Solterra', 'Wrangler 4xe', 'ProMaster 2500', 'Corsair',
           'Savana 2500', 'Pacifica Hybrid', 'ZDX', 'Altima', 'EQS 450',
           'ProMaster 3500', 'XT5', 'Gladiator', 'QX50', 'Versa',
           'AMG GLE 53', 'A5 Sportback', 'Nautilus', 'Trailblazer',
           'i4 Gran Coupe', 'Escape', 'Bronco Sport', 'Elantra HEV',
           'RX 500h', 'Prologue', 'i5', 'MX-5 Miata RF', 'ID.4', 'CR-V',
           'Silverado 2500', 'Sierra 3500', 'Legacy', 'i7', 'M235 Gran Coupe',
           'Range Rover Evoque', 'Odyssey', 'Sierra 2500', 'Titan',
           'RS e-tron GT', 'Edge', 'Discovery Sport', 'Sprinter 3500',
           'XC90 Recharge Plug-In Hybrid', 'Sorento', 'Frontier', 'HR-V',
           'Niro', 'Encore GX', 'Electrified G80', 'GLE 450', 'GLS 450',
           'Trax', 'Defender', 'SQ8 e-tron', 'Sorento Hybrid', 'Envision',
           'Bronco', 'Palisade', '740', 'Passport', 'LYRIQ', 'Corolla Cross',
           'Equinox EV', 'Grand Wagoneer', 'Kona', 'QX55', 'Corolla', 'F-150',
           'A3', 'Enclave', 'Sentra', 'I-PACE', 'RAV4 Prime', 'Voyager',
           'Sierra 1500', 'Transit Connect', 'Maverick', 'Transit-350',
           'Pathfinder', 'GLA 250', 'Telluride', 'CX-90', 'Electrified GV70',
           'S60 Recharge Plug-In Hybrid', 'XT6', 'Impreza', 'CX-70', 'X3',
           'C40 Recharge Pure Electric', 'ProMaster 1500', 'Soul', '300',
           'AMG C 43', 'Forte']

Engine = ['24V GDI DOHC Twin Turbo', 'OHV', 
          '6.2L V-8 gasoline direct injection, variable valve contr',
           '16V MPFI OHV', '24V DDI OHV Turbo Diesel', '24V MPFI DOHC',
           '32V DDI OHV Turbo Diesel', '16V GDI DOHC Turbo Hybrid',
           'ar 3.6L V-6 DOHC, variable valve control, regular unleade',
           '16V GDI DOHC Turbo', 'oled Turbo Diesel I-6 6.7 L/408',
           '16V PDI DOHC Turbo', 'c',
           '4 gasoline direct injection, DOHC, variable valve control',
           '16V PDI DOHC', 'DOHC', '24V PDI DOHC Flexible Fuel',
           '16V GDI OHV', '16V MPFI DOHC', '24V GDI DOHC',
           'gasoline direct injection, DOHC, intercooled turbo, premi',
           '16V GDI DOHC Hybrid', '24V GDI SOHC',
           'gasoline direct injection, DOHC, variable valve control,',
           'c Motor',
           '4 gasoline direct injection, DOHC, Multiair variable valv',
           '4 gasoline direct injection, DOHC, CVVT variable valve co',
           '24V PDI DOHC Twin Turbo',
           'ream 2.5L I-4 port/direct injection, DOHC, CVVT variable',
           '24V GDI DOHC Turbo',
           'MAX 3.4L V-6 port/direct injection, DOHC, variable valve',
           '4 DOHC, CVTCS variable valve control, regular unleaded, e',
           '12V GDI DOHC Turbo',
           'o 1.5L I-3 gasoline direct injection, DOHC, CVTCS variabl',
           'ne 3L I-6 gasoline direct injection, DOHC, variable valve',
           '4 port/direct injection, DOHC, CVVT variable valve contro',
           'oled Turbo Premium Unleaded V-6 3.0 L/183',
           'High Output 6.7L I-6 diesel direct injection, VVT interc',
           'DOHC 16V LEV3-SULEV30', '16V DDI DOHC Turbo Diesel', 'Turbo DOHC',
           'TIV-G 2.5L I-4 gasoline direct injection, DOHC, variable',
           '6 gasoline direct injection, variable valve control, regu',
           '24V MPFI DOHC Hybrid', '16V GDI DOHC',
           'ne 2L I-4 gasoline direct injection, DOHC, variable valve',
           'o 2L I-4 port/direct injection, DOHC, variable valve cont',
           '8 variable valve control, regular unleaded, engine with 4',
           '1.3L I-3 gasoline direct injection, DOHC, variable valve',
           't 1.5L I-3 port/direct injection, DOHC, Ti-VCT variable v',
           'oBoost', '>\n\n    \n    <dt>VIN</dt>\n     ZACNDFAN0R3A12168',
           '24V VVT',
           '.6L I-4 gasoline direct injection, DOHC, D-CVVT variable',
           '6.7L I-6 diesel direct injection, VVT intercooled turbo,',
           '16V PDI DOHC Turbo Hybrid', '24V DDI DOHC Turbo Diesel', ';',
           'dd>\n\n    \n    <dt>VIN</dt>\n     1V2BMPE85RC003636',
           'gasoline direct injection, DOHC, i-VTEC variable valve co',
           '6.6L V-8 diesel direct injection, intercooled turbo, die', 'der',
           '12V PDI DOHC Turbo', 'oled Turbo Premium Unleaded I-4 2.0 L/122',
           'ce 5.6L V-8 gasoline direct injection, DOHC, variable val',
           'c ZEV',
           '4 port/direct injection, DOHC, variable valve control, in',
           'Unleaded V-8 5.6 L/339', '12V GDI OHV',
           't 2L I-4 gasoline direct injection, DOHC, variable valve',
           '6 port/direct injection, DOHC, variable valve control, re',
           '6 gasoline direct injection, i-VTEC variable valve contro',
           '6 DOHC, variable valve control, regular unleaded, engine',
           '5.3L V-8 gasoline direct injection, variable valve contr',
           '6 DOHC, VVT variable valve control, engine with cylinder',
           'ar 3.6L V-6 DOHC, VVT variable valve control, regular unl',
           '32V GDI DOHC Twin Turbo', '24V DOHC',
           '<dt>VIN</dt>\n     3GN7DNRPXRS232327',
           'diesel direct injection, DOHC, intercooled turbo, diesel,',
           '24V PDI DOHC Twin Turbo Hybrid', 'EcoBoost',
           '<dt>VIN</dt>\n     1FMUK7HH1SGA05728', 'ER',
           '<dt>VIN</dt>\n     3C63R3HLXRG198198',
           'ream 1.6L I-4 gasoline direct injection, DOHC, CVVD varia',
           'd>\n\n    \n    <dt>VIN</dt>\n     SADHM2S12R1631756',
           '16V PDI DOHC Hybrid', 'c ZEV 320hp',
           'gasoline direct injection, DOHC, iVCT variable valve cont',
           '4 DOHC, variable valve control, regular unleaded, engine',
           '6 gasoline direct injection, DOHC, variable valve control',
           'rbo Regular Unleaded I-6 3.0 L/183',
           'II 3.8L V-6 gasoline direct injection, DOHC, D-CVVT varia',
           'd>\n\n    \n    <dt>VIN</dt>\n     7FARS4H71SE000866',
           '16V MPFI DOHC Hybrid', 'o',
           '4L V-8 VVT variable valve control, regular unleaded, engi',
           'DOHC, D-CVVT variable valve control, regular unleaded, en',
           '8 gasoline direct injection, variable valve control, regu']

Trim = ['Series II', 'Laredo', 'Denali', 'Pursuit', 'Laramie', 'Platinum',
           'Base', 'Lariat Super Duty', 'Limited', 'Altitude', 'Latitude',
           'Tradesman', '2.5T Limited', '2LT', '2.5T XRT', 'Timberline',
           '1.5T SE', '1.4T S', 'R/T', 'SEL', '2.5L SEL', 'XLT', 'Touring-L',
           'SV', '148 WB Medium Roof Cargo', 'Trailhawk', 'GT', '1.4T SE',
           'Premium', 'RST', 'EX', '3LT', 'SLE', 'Sport S', 'Preferred',
           'Advance', 'Wilderness', '2.0T SEL', 'SE Standard Range',
           'S line Premium', 'Light Long Range', 'R/T EAWD',
           '2.0T Peak Edition SE w/Technology', 'xDrive40i', 'SE',
           'Series II Carbide 4x4', 'S', 'SL', 'Avenir', 'SLT', 'XL',
           'Premium Plus', 'Tradesman Crew Cab 4x4 8&#39; Box',
           '55 Premium Plus', 'R/T Plus', 'Custom', 'LT', 'WT', 'SXT',
           'Standard Roof', 'Sport Touring', 'SEL Convenience', 'X-Line',
           'Sport', '4-Door Sahara 4x4', 'Blue', 'Scat Pack', 'Calligraphy',
           '4x4', 'LS', 'Rubicon', 'Disney100 Platinum Edition', 'High Roof',
           'Reserve', 'Work Van', 'Select', 'A-SPEC', '2.5 SV', 'GT AWD',
           'Anniversary Edition', 'Base 4MATIC', 'Hornet Gt Awd', 'Luxury',
           'Technology', '1.5T S', 'LUXE', '1.6 SV', 'S line Premium Plus',
           'RS', 'eDrive40', 'Sahara', 'Active', 'Outer Banks', 'XRT',
           'Laramie Crew Cab 4x4 8&#39; Box', '2.0T SEL R-Line',
           'Tradesman/SLT/Laramie/Limited', 'F SPORT PERFORMANCE',
           'Laramie Mega Cab 4x4 6&#39;4&#39; Box', 'LT Trail Boss', '1.6 SR',
           'SE 2.4', 'TOURING', 'N Line', 'SR', 'M60', '1.5T SEL',
           'Hornet R/T Plus Eawd', 'Grand Touring', 'Standard',
           'Hybrid Sport-L', 'Big Horn', 'Wind', 'M50', 'eDrive50',
           'i xDrive', 'SX', 'X-Pro Prestige', 'Dynamic SE', 'Elite',
           'Longhorn', 'FWD RS', 'Premium 55 TFSI e S line quattro S tronic',
           'quattro', 'ST-Line', '1LT', '2.5T NIGHT',
           '170 WB High Roof Extended Cargo',
           'T8 Plus Bright Theme 7 Passenger', 'Premium Luxury', 'Series III',
           'LX', 'Touring', '4MATIC', 'Rubicon X', 'Custom Trail Boss',
           'Touring L', 'Big Bend', 'Overland', 'P400 X-Dynamic SE',
           '55 Prestige', 'M60i', 'GT Plus AWD', 'Latitude Lux', 'SX Touring',
           'Wildtrak', 'R/T Plus EAWD', 'Power Wagon', 'Sport-L', 'i',
           'Summit', 'ST-Line Elite', 'Essence', 'TrailSport', 'Sport w/1SF',
           'ZR2', 'EX-L', 'LE', '1794 Edition', 'SENSORY', '1.4T SEL',
           'Tradesman 4x4 Crew Cab 8 Box', 'STX', 'SPORT', 'Titanium',
           'EV400 R-Dynamic HSE', 'XSE', 'xDrive40', 'Crew 144 WB',
           'Sport w/1SJ', 'Pro', 'Hornet R/T Eawd', '2.5L SE',
           'Denali Ultimate', 'Lariat', 'AT4', 'SL 4WD', 'GT Plus',
           '144 WB Standard Roof Crew', 'Free Wheeling', 'ACTIV',
           'King Ranch', '144 WB Standard Roof Passenger', 'SX X-Pro',
           '3.3 Turbo Premium Plus', 'SX-Prestige', 'Advanced', 'M70',
           '3.3 Turbo S Premium', 'T8 Plus Dark Theme', 'Luxury FWD',
           'sDrive30i', 'Tradesman Regular Cab 4x4 8&#39; Box',
           'Twin Ultimate', 'Low Roof', 'LXS', 'SV Intelligent AWD']

Exterior_color = ['White', 'Metallic', 'Summit White', 'White Knuckle Clearcoat',
       'Silver', 'Bright White Clearcoat', 'Carbonized Gray Metallic',
       'White Pearl', 'Silver Zynith',
       'Granite Crystal Metallic Clearcoat', 'Atlas',
       'Baltic Gray Metallic Clearcoat', 'Sterling Gray Metallic',
       'Blue Stone', 'Deep Ocean Blue', 'Star White', 'Blue',
       'Pyrite Silver Metallic', 'HOT TAMALE', 'Ebony', 'Diamond Black',
       'Radiant Red', 'Granite', 'Oxford White', 'Yacht Blue',
       'Vapor Blue', 'Steel Gray', 'Copper Bronze',
       'Hydro Blue Pearlcoat', 'Machine Gray Metallic', 'Gray',
       'DB Black Crystal Clearcoat', 'Magnetite', 'Silver Mist Metallic',
       'Glacier White Metallic', 'Pure White', 'Portofino Gray',
       'Aurora Black Pearl', 'Night', '8 Ball', 'Q BALL', 'Gravity Gray',
       'Blue Steel', 'Avocado Green', 'Cyber Gray', 'Shimmering Silver',
       'Black Sapphire Metallic', 'Ice Cap', 'Black',
       'Aspen White Tricoat', 'Sunrise Red Metallic', 'Gun Metallic',
       'Deep Ocean Blue Pearl', 'Velvet Red Pearlcoat',
       'Boulder Gray Pearl', 'Polar White', 'Ocean Blue Metallic',
       'Vapor Gray', 'Ebony Twilight Metallic', 'Ultra Blue Metallic',
       'Gray Metallic', 'Pearl White', 'Soul',
       'Rapid Red Metallic Tinted Clearcoat', 'Gold', 'Silver Gray',
       'Radiant Red Metallic', 'Amazon Gray', 'Red Line',
       'Glacial White Pearl', 'Laser Blue Pearlcoat', 'Race Red',
       'Twilight Blue Metallic', 'Green', 'Midnight Sky', 'Galactic',
       'Earl Clearcoat', 'Rhodium White Premium',
       'Infinite Black Metallic', 'Jet Black Mica', 'Gray Cray',
       'Deep Crystal Blue Mica', 'Hot Tamale', 'Silver Zynith Clearcoat',
       'Pure Gray W/Black Roof', 'Crystal White Tri-Coat',
       'Diamond Black Crystal Pearlcoat', 'Anvil Clearcoat',
       'High Velocity Clearcoat', 'Slate Gray', 'Aspen White', 'SILVER',
       'Rhodium White Metallic', 'Navarra Blue Metallic',
       'Crimson Metallic', 'Blu Bayou', 'Pearlcoat', 'Shadow Black',
       'Riverrock Green', 'Serenity White', 'Patriot Blue Pearlcoat',
       'Silver Bird Metallic', 'Caviar', 'Slate Gray Metallic', 'BX',
       'Titanium Gray', 'Deep Black Pearl Effect',
       'Scarlet Ember Tintcoat', 'Mineral White', 'Sage Gray',
       'Sting Gray Clearcoat', 'Phantom Black', 'Deep Sea', '8 BALL',
       'Billet Silver Metallic Clearcoat', 'Snowflake White Pearl',
       'Obsidian Black Metallic', 'Still Night Pearl',
       'Granite Crystal Clearcoat Metallic', 'Dark Ash Metallic',
       'Mosaic Black Metallic', 'Bright Silver Clearcoat Metallic',
       'Sterling Metallic', 'Artisan Red Premium', 'Red',
       'Ice Silver Metallic', 'Acapulco Gold', 'Sonic',
       'Lunar Silver Metallic', 'Ebony Black', 'Arroios Grey',
       'White Frost Tri-Coat', 'Daytona Gray Pearl', 'Opal White Pearl',
       'Super Black', 'Tactical Green Metallic',
       'Opal White Pearl Effect', 'Glacier White', 'Black Obsidian',
       'Aspen White Tricoat/Super Black', 'Fuji White', 'Gray White',
       'Anvil Clear Coat', 'Radiant Red Metallic II', 'Bright',
       'Silver Metallic', 'Wolf Gray',
       'PAS Baltic Grey Metallic Clear Coat', 'Deep Ocean Pearl',
       'Aurora Black', 'Agate Black Metallic', 'Uyuni White',
       'Black Pearl', 'Artisan Red Metallic', 'Eiger Grey', 'Alpine Gray',
       'Bright White', 'Cayenne Orange Metallic', 'Black Sapphire',
       'Bikini Pearl Coat', 'Flame Red Clearcoat', 'Platinum White Pearl',
       'Fathom Blue Pearlcoat', 'Soul Red Crystal Metallic',
       'Alpine White', 'DB Black Clearcoat', 'Gondwana Stone',
       'Black Clearcoat', 'WHITE', 'Mythos Black Metallic',
       'Mineral White Metallic', 'Snow White Pearl', 'Runway Red',
       'Agate Black', 'Star White Metallic Tri-Coat',
       'Azure Gray Metallic', 'Autumn Green',
       'Silver Zynith Metallic Clearcoat', 'Pearl', 'Teal',
       'Vapor Blue Metallic', 'Baltic Gray', 'Q Ball', 'Carbon Blue',
       'Aventurin Red Metallic', 'Steel / Graphite',
       'Olive Green Pearlcoat', 'Blue Dusk', 'Volcanic Red',
       'Hyper White', 'Deep Black Pearl', 'Electric Blue Metallic',
       'Iconic Silver Metallic', 'Glacier Gray', 'Hampton Gray', 'Sky',
       'Crystal White Tricoat', 'Iconic Silver', 'Gray Pearl',
       'Onyx Black', 'Celestial Silver Metallic', 'CELESTITE', 'Glacier',
       'Rhodium', 'Canyon', 'Stellar Black Metallic', 'Smoked Mesquite',
       'Graphite Shadow', 'Boulder Gray Metallic', 'Abyss Black Pearl',
       'Eruption Green Metallic', 'Supersonic Red',
       'Florett Silver Metallic', 'Machine', 'Orange Pearl',
       'Iridium Silver', 'Emerald', 'Radiant White', 'Cloud White',
       'Cyber Gray Metallic', 'Santorini Black', 'Silver Sky Metallic',
       'Titan Gray', 'Celestial Metallic', 'Gravity Gold Matte',
       'Frozen White', 'Magnetic Gray Metallic', 'Sting-Gray Clearcoat',
       'Sarge Green Clearcoat', 'Mirage', 'Cactus Green / Gray',
       'Red Metallic', 'Crystal White Pearl', 'Modern Steel Metallic',
       'Glacier White Pearl', 'Blue Steele', 'Arctic White',
       'Tanzanite Blue II Metallic', 'Argent Silver Metallic',
       'Sparkling', 'Jet Black', 'Delmonico Red Pearlcoat',
       'Hot Pepper Red Metallic Tinted Clearcoat', 'Platinum',
       'Midnight Black', 'Vik Black', 'Urban Gray Pearl',
       'Destroyer Gray Clearcoat', 'Onyx Black Metallic', 'Pure Red',
       '41w', 'Scarlet Ember', 'Platinum Gray Metallic',
       'Scarlet Ember Tintcoat/Super Black', 'Crystal Black Silica',
       'Midnight Sapphire', 'Gloss Black', 'Aspen White / Super Black',
       'Jungle Green', 'Cactus Gray', 'Pearl White Tricoat',
       'Wheatland Yellow']

Interior_color = ['Global Black', 'Teak/Light Shale', 'Black', 'Gray', 'Black Onyx',
           'Dark Gray', 'Beige', 'Ebony', 'Black Cloud', 'Titan Black',
           'Jet Blk', 'Graphite', 'Dark Palazzo Gray', 'Jet Black',
           'Jet Blk Premium Clth', 'Diesel Gray/Black', 'Pearl Beige',
           'Beige / Black', 'Cognac', 'Charcoal', 'Black Interior Color',
           'Steel Gry Premium Cl', 'Medium Ash Gray', 'Greige', 'White',
           'Pebble Gray', 'Medium Earth Gray', 'Jet Black w/Red Accents',
           'Tacora Red', 'Ebony Black', 'Ebony/Roast', 'Medium Gray',
           'Mauro Brown', 'Nutmeg', 'Ruby Red', 'Gideon/Very Dark Atmosphere',
           'Dark Walnut / Slate', 'Okapi Brown', 'Lt Mountain Brown/Brown',
           'Jet Black With Red Accents', 'Gry Lthette', 'Black / Diesel Gray',
           'Sepia / Black', 'Sea Salt', 'Medium Pewter', 'Nh-731p/Black',
           'Dk Palazzo Gry Fron', 'Black/Alloy/Black', 'Griege',
           'Ebony W/Red Stitching', 'Medium Sandstone', 'Dark Green',
           'Brown/Blk', 'Gray / Black', 'Oyster', 'Tupelo', 'Red',
           'Noir w/Santorini Blue Accents', 'Tupelo/Black', 'Melange',
           'Volcano Brown', 'Black SofTex-trimmed\xa0[softex]',
           'Wicker Beige/Black', 'Ash', 'Tan', 'Light Platinum', 'Bk',
           'Diesel Gray / Black', 'Sandstone', 'Mojave Dusk/Onyx',
           'Monaco Red', 'Dark Galvanized', 'Macchiato Beige',
           'Medium Soft Ceramic', 'Black w/Red Accents', 'Space Gray',
           'Boulder', 'Ruby Red/Black', 'Alpine Umber', 'Dune',
           'Wicker Beige/Global Black', 'Nh-797m/Black',
           'Dk Palazzo Gry Clth Front', 'Silverstone', 'Java', 'Caramel',
           'gray', 'Dark Palazzo', 'Gray/Black', 'Navy Pier']


